export default function Terms() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-14">
      <h1 className="text-3xl font-extrabold text-white mb-2">Terms of Service</h1>
      <p className="text-gray-500 text-sm mb-8">Last updated: December 2024</p>

      {[
        {
          title: '1. Acceptance of Terms',
          content: 'By accessing and using SmartToolkit (smarttoolkit.space), you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, please do not use our website.'
        },
        {
          title: '2. Description of Service',
          content: 'SmartToolkit provides free, browser-based online tools including a password generator, 2FA code reader, word counter, character counter, meta tag generator, and keyword density checker. These tools are provided "as is" without any warranty of any kind.'
        },
        {
          title: '3. Acceptable Use',
          content: 'You agree to use SmartToolkit only for lawful purposes. You must not use our tools to generate passwords or codes for unauthorized access to systems, to create content that violates applicable laws, or for any purpose that could harm others.'
        },
        {
          title: '4. Disclaimer of Warranties',
          content: 'SmartToolkit tools are provided on an "as is" and "as available" basis. We make no warranties, expressed or implied, including but not limited to the accuracy, reliability, or completeness of any output generated by our tools. Use the tools at your own risk.'
        },
        {
          title: '5. Limitation of Liability',
          content: 'SmartToolkit shall not be liable for any indirect, incidental, special, or consequential damages resulting from your use of or inability to use our tools. This includes but is not limited to damages resulting from loss of data, loss of revenue, or security incidents.'
        },
        {
          title: '6. Intellectual Property',
          content: 'The SmartToolkit website, its design, and its content are owned by SmartToolkit. You may not reproduce, distribute, or create derivative works from our content without express written permission.'
        },
        {
          title: '7. Changes to Terms',
          content: 'We reserve the right to modify these terms at any time. Continued use of SmartToolkit after changes are posted constitutes acceptance of the revised terms.'
        },
        {
          title: '8. Contact',
          content: 'For questions regarding these Terms of Service, please use our Contact page.'
        },
      ].map(section => (
        <div key={section.title} className="mb-8">
          <h2 className="text-lg font-bold text-white mb-3">{section.title}</h2>
          <p className="text-gray-400 text-sm leading-relaxed">{section.content}</p>
        </div>
      ))}
    </div>
  )
}
